--- #YAML:1.0
name:               WebService-TWFY-API
version:            0.03
abstract:           API interface for TheyWorkForYou.com
author:
    - Spiros Denaxas (s [dot] denaxas [@] gmail [dot]com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Exception:  0.24
    Test::Simple:     0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
